version: '3.7'

services: 
  todo-mvc:
    build: .
    volumes:
      - .:/webapp
      - ~/.m2: /root/.m2
    working_dir: /webapp
    ports: 
      - '8080:8080'
    command: mvn clean spring-boot:run
